import { config } from '../config.js';
export const ECOSYSTEM={
 multiAI:[['CrewAI','role agents/flows'],['LangGraph','stateful graph orchestration'],['Microsoft Agent Framework','enterprise handoffs/workflows'],['CAMEL','communicating agent societies'],['MetaGPT','software-team SOPs'],['ChatDev','virtual software company']],
 evaluation:[['Promptfoo','prompt/agent evals + red team'],['DeepEval','LLM/agent trajectory metrics'],['Inspect AI','controlled agent evaluations'],['TruLens','LLM/RAG feedback evaluation'],['ARES','RAG relevance/faithfulness evaluation'],['OpenAI Evals','benchmark/regression patterns']],
 tokenOptimization:[['Headroom','context compression/shared context'],['LLMLingua','prompt compression'],['LongLLMLingua','long-context compression'],['LLMLingua-2','task-agnostic compression'],['GPTCache','semantic response caching'],['DSPy','metric-driven prompt optimization']],
 humanLike:[['Mem0','persistent personalized memory'],['Letta','stateful identity + editable memory'],['Zep','temporal memory/knowledge graph'],['Graphiti','temporal knowledge graph'],['Hindsight','retain/recall/reflect learning memory'],['LangMem','long-term memory tooling']],
 discord:[['discord.js','native Discord API runtime'],['Jeeves','AI moderation/cases/automod'],['Red-DiscordBot','modular moderation/admin'],['Modmail Bot','private staff support threads'],['Assist','dashboard/moderation/automod'],['Disnake','Discord event/rate-limit patterns']]
};
export function ecosystemSummary(){return Object.fromEntries(Object.entries(ECOSYSTEM).map(([k,v])=>[k,{count:v.length,projects:v.map(x=>x[0])}]));}
export function buildProfessionalSystem(analysis={}){const l=['ECOSYSTEM MODE: professional agent engineering.','Use explicit specialist roles; do not make every model repeat the same work.','Use a small state machine: plan → execute → verify → revise → finalize.','Prefer evidence over consensus; reviewers may reject the majority.','Use deterministic checks before LLM judgement.','Compress only when useful; preserve identifiers, constraints, code, citations and output formats.','Reuse safe semantic results only when the request is not time-sensitive.','Personalize from durable memory; never invent or expose private memory.','Speak naturally without claiming actions that were not performed.'];if(analysis.kinds?.includes('coding'))l.push('Coding roles: architect → implementer → reviewer → test engineer.');if(analysis.wantsWeb||analysis.kinds?.includes('research'))l.push('Research roles: researcher → source checker → skeptic → synthesizer.');if(analysis.kinds?.includes('discord'))l.push('Discord roles: policy checker → permission checker → action planner → audit logger.');return l.join('\n');}
export function buildRolePlan(a={}){if(a.kinds?.includes('coding'))return['architect','implementer','reviewer','test-engineer'];if(a.wantsWeb||a.kinds?.includes('research'))return['researcher','source-checker','skeptic','synthesizer'];if(a.kinds?.includes('discord'))return['policy-checker','permission-checker','action-planner','auditor'];if(a.kinds?.includes('math'))return['solver','checker','counterexample-reviewer'];return['lead','reviewer','editor'];}
export function evaluateLightweight(candidate,a={}){const t=String(candidate||''),issues=[];if(!t.trim())issues.push('empty-output');if(a.wantsWeb&&!/https?:\/\//i.test(t))issues.push('web-answer-without-visible-source');if(a.wantsFile&&!/```[\s\S]*```/m.test(t))issues.push('file-request-without-code-block');if(a.kinds?.includes('coding')&&/TODO|FIXME/i.test(t))issues.push('unfinished-marker');if(/I ran|đã chạy|đã kiểm thử|tested successfully/i.test(t)&&!/test environment|môi trường test|static check|kiểm tra tĩnh/i.test(t))issues.push('unverified-execution-claim');
if(a.wantsWeb && /\[\d+\]/.test(t) && !/https?:\/\//i.test(t)) issues.push('web-citation-without-url');return{ok:!issues.length,issues};}
export function shouldEnableSemanticCache(a={}){
  if (!config.ecosystem.semanticCache.enabled) return false;
  if (a.wantsWeb || a.webMode === 'news' || a.explicitAI) return false;
  if (a.wantsFile || a.kinds?.includes('coding') || a.kinds?.includes('creative')) return false;
  return a.difficulty === 'easy' || a.difficulty === 'medium';
}
