import {ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,PermissionsBitField} from 'discord.js';
import {listProviders,listModels,upsertProvider,addModel,deleteProvider,toggleModel,setSetting,getSetting} from './db.js';
import {catalog,suggestedModels,testProvider} from './providers.js';
const ok='🟢',off='🔴';
function adminAllowed(i){if(i.memberPermissions?.has(PermissionsBitField.Flags.Administrator))return true;const ids=(process.env.ADMIN_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);const roles=(process.env.ADMIN_ROLE_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);return ids.includes(i.user.id)||i.member?.roles?.cache?.some(r=>roles.includes(r.id));}
function home(){return new EmbedBuilder().setTitle('🤖 AI COUNCIL • ADMIN').setDescription('Quản lý API, model, routing và hệ thống ngay trong Discord.\n\n🔐 API key được mã hóa trước khi lưu PostgreSQL.\n🆓 Có thể ưu tiên model free-tier.').setColor(0x5865f2).setTimestamp();}
function rows(){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_ai').setLabel('AI / MODEL').setEmoji('🤖').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('adm_api').setLabel('API').setEmoji('🔑').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('adm_route').setLabel('ROUTING').setEmoji('🧠').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('adm_health').setLabel('HEALTH').setEmoji('🩺').setStyle(ButtonStyle.Success)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_stats').setLabel('THỐNG KÊ').setEmoji('📊').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('adm_reload').setLabel('RELOAD').setEmoji('🔄').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('adm_close').setLabel('ĐÓNG').setEmoji('✖️').setStyle(ButtonStyle.Danger))];}
async function dashboard(i){await i.reply({embeds:[home()],components:rows(),ephemeral:true});}
export async function registerAdmin(client){const cmd=await client.application.commands.fetch();if(!cmd.find(c=>c.name==='admin'))await client.application.commands.create({name:'admin',description:'Mở bảng điều khiển AI Council'});client.on('interactionCreate',async i=>{try{if(i.isChatInputCommand()&&i.commandName==='admin'){if(!adminAllowed(i))return i.reply({content:'⛔ Bạn không có quyền dùng /admin.',ephemeral:true});return dashboard(i);}if(!i.isButton()&&!i.isStringSelectMenu()&&!i.isModalSubmit())return;if(!adminAllowed(i))return i.reply({content:'⛔ Không có quyền.',ephemeral:true});if(i.customId==='adm_close')return i.update({content:'Đã đóng bảng quản trị.',embeds:[],components:[]});if(i.customId==='adm_reload')return dashboardEdit(i);if(i.customId==='adm_ai')return aiPanel(i);if(i.customId==='adm_api')return apiPanel(i);if(i.customId==='adm_route')return routePanel(i);if(i.customId==='adm_health')return healthPanel(i);if(i.customId==='adm_stats')return statsPanel(i);if(i.customId==='adm_add_api')return addApiModal(i);if(i.customId==='adm_add_model')return addModelModal(i);if(i.customId==='adm_api_select')return apiSelected(i);if(i.customId==='adm_model_select')return modelSelected(i);if(i.customId==='adm_suggest')return suggestionPanel(i);if(i.customId==='adm_provider_select')return providerSelected(i);if(i.customId==='adm_test')return testSelected(i);if(i.isModalSubmit()&&i.customId==='adm_api_modal')return saveApi(i);if(i.isModalSubmit()&&i.customId==='adm_model_modal')return saveModel(i);}catch(e){if(i.deferred||i.replied)await i.followUp({content:`❌ ${e.message}`,ephemeral:true}).catch(()=>{});else await i.reply({content:`❌ ${e.message}`,ephemeral:true}).catch(()=>{});}});}
async function dashboardEdit(i){const ps=await listProviders(),ms=await listModels();const e=home().addFields({name:'Providers',value:`${ps.filter(x=>x.enabled).length}/${ps.length} đang bật`,inline:true},{name:'Models',value:`${ms.filter(x=>x.enabled).length}/${ms.length} đang bật`,inline:true});return i.update({embeds:[e],components:rows()});}
async function aiPanel(i){const ms=await listModels();const e=new EmbedBuilder().setTitle('🤖 AI / MODEL').setDescription(ms.length?ms.slice(0,20).map(m=>`${m.enabled?ok:off} **${m.name}** · ${m.provider}\n${m.description||'Chưa có mô tả'} · ${m.free_tier?'🆓 free-tier':''}`).join('\n\n'):'Chưa có model.').setColor(0x57f287);const s=new StringSelectMenuBuilder().setCustomId('adm_model_select').setPlaceholder('Chọn model để bật/tắt').addOptions(ms.slice(0,25).map(m=>({label:`${m.provider} / ${m.name}`.slice(0,100),value:String(m.id),description:(m.description||'Model').slice(0,100)})));return i.update({embeds:[e],components:[new ActionRowBuilder().addComponents(s),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_add_model').setLabel('Thêm model').setEmoji('➕').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('adm_suggest').setLabel('Gợi ý model').setEmoji('💡').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('adm_api').setLabel('API').setEmoji('🔑').setStyle(ButtonStyle.Secondary))]});}
async function apiPanel(i){const ps=await listProviders();const e=new EmbedBuilder().setTitle('🔑 API PROVIDERS').setDescription(ps.length?ps.map(p=>`${p.enabled?ok:off} **${p.name}** · ${p.base_url||catalog()[p.name]?.base||'custom'}`).join('\n'):'Chưa có API.').setColor(0xfee75c);return i.update({embeds:[e],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_add_api').setLabel('Thêm / cập nhật API').setEmoji('➕').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('adm_api_select').setLabel('Chọn provider').setEmoji('🔧').setStyle(ButtonStyle.Primary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_ai').setLabel('AI / MODEL').setEmoji('🤖').setStyle(ButtonStyle.Secondary))]});}
async function routePanel(i){const d=await getSetting('default_model',process.env.DEFAULT_MODEL||'chưa chọn');const p=await getSetting('default_provider',process.env.DEFAULT_PROVIDER||'gemini');const free=await getSetting('free_first','true');return i.update({embeds:[new EmbedBuilder().setTitle('🧠 ROUTING').setDescription(`Provider mặc định: **${p}**\nModel mặc định: **${d}**\nFree-first: **${free==='true'?'BẬT':'TẮT'}**\n\nRouter sẽ ưu tiên model free-tier đang enabled, sau đó fallback sang model khác nếu admin đã cấu hình.`).setColor(0x5865f2)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_ai').setLabel('AI / MODEL').setEmoji('🤖').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('adm_reload').setLabel('Reload').setEmoji('🔄').setStyle(ButtonStyle.Secondary))]});}
async function healthPanel(i){const ps=await listProviders();const lines=[];for(const p of ps.slice(0,12)){const ms=(await listModels()).filter(m=>m.provider_id===p.id&&m.enabled);if(!ms[0]){lines.push(`🟡 **${p.name}** · chưa có model`);continue}try{const r=await testProvider(p.name,ms[0].name);lines.push(`${r.ok?ok:off} **${p.name}** / ${ms[0].name} · ${r.latency}ms`)}catch(e){lines.push(`${off} **${p.name}** · ${e.message.slice(0,80)}`)}}return i.update({embeds:[new EmbedBuilder().setTitle('🩺 HEALTH CHECK').setDescription(lines.join('\n')||'Chưa có provider.').setColor(0x57f287)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_api').setLabel('API').setEmoji('🔑').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('adm_ai').setLabel('Models').setEmoji('🤖').setStyle(ButtonStyle.Secondary))]});}
async function statsPanel(i){const ps=await listProviders(),ms=await listModels();return i.update({embeds:[new EmbedBuilder().setTitle('📊 THỐNG KÊ').setDescription(`Providers: **${ps.length}**\nProviders bật: **${ps.filter(x=>x.enabled).length}**\nModels: **${ms.length}**\nModels bật: **${ms.filter(x=>x.enabled).length}**\nFree-tier models: **${ms.filter(x=>x.free_tier).length}**`).setColor(0x5865f2)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_health').setLabel('Health').setEmoji('🩺').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('adm_reload').setLabel('Reload').setEmoji('🔄').setStyle(ButtonStyle.Secondary))]});}
function addApiModal(i){return i.showModal(new ModalBuilder().setCustomId('adm_api_modal').setTitle('Thêm / cập nhật API').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('provider').setLabel('Provider (gemini/groq/openrouter...)').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('key').setLabel('API key').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('base').setLabel('Base URL (để trống nếu mặc định)').setStyle(TextInputStyle.Short).setRequired(false))));}
async function saveApi(i){const name=i.fields.getTextInputValue('provider').trim().toLowerCase(),key=i.fields.getTextInputValue('key').trim(),base=i.fields.getTextInputValue('base').trim();await upsertProvider({name,apiKey:key,baseUrl:base});return i.reply({content:`✅ Đã lưu API **${name}**. Key đã được mã hóa trong PostgreSQL.`,ephemeral:true});}
function addModelModal(i){return i.showModal(new ModalBuilder().setCustomId('adm_model_modal').setTitle('Thêm model').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('provider').setLabel('Provider').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('name').setLabel('Model ID').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Mô tả').setStyle(TextInputStyle.Paragraph).setRequired(false)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('role').setLabel('Role: general/coding/reasoning/fast').setStyle(TextInputStyle.Short).setRequired(false)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('free').setLabel('Free-tier? true/false').setStyle(TextInputStyle.Short).setRequired(false))));}
async function saveModel(i){const ps=await listProviders(),name=i.fields.getTextInputValue('provider').trim().toLowerCase(),p=ps.find(x=>x.name===name);if(!p)return i.reply({content:'❌ Provider chưa tồn tại. Hãy thêm API trước.',ephemeral:true});await addModel({providerId:p.id,name:i.fields.getTextInputValue('name').trim(),description:i.fields.getTextInputValue('description'),role:i.fields.getTextInputValue('role')||'general',freeTier:(i.fields.getTextInputValue('free')||'true').toLowerCase()==='true'});return i.reply({content:'✅ Model đã được lưu vào PostgreSQL.',ephemeral:true});}
async function modelSelected(i){const id=Number(i.values[0]);const enabled=await toggleModel(id);return i.reply({content:`${enabled?ok:off} Model đã ${enabled?'bật':'tắt'}.`,ephemeral:true});}
async function apiSelected(i){const ps=await listProviders();const p=ps.find(x=>x.name===i.values[0]);if(!p)return i.reply({content:'Không tìm thấy provider.',ephemeral:true});await deleteProvider(p.id);return i.reply({content:`🗑 Đã xóa **${p.name}** và các model của provider.`,ephemeral:true});}
async function suggestionPanel(i){const text=Object.entries(catalog()).map(([k,v])=>`**${v.label}**\n${v.desc}\n${suggestedModels(k).slice(0,3).map(m=>'• `'+m.name+'` — '+m.description).join('\n')}`).join('\n\n');return i.update({embeds:[new EmbedBuilder().setTitle('💡 MODEL CATALOG / GỢI Ý').setDescription(text.slice(0,4000)).setColor(0xfee75c)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_add_model').setLabel('Thêm model').setEmoji('➕').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('adm_ai').setLabel('Quay lại').setEmoji('↩️').setStyle(ButtonStyle.Secondary))]});}
async function providerSelected(i){return i.reply({content:'🔧 Chọn provider ở menu này sẽ là thao tác xóa. Nếu muốn cập nhật, dùng “Thêm / cập nhật API” để ghi đè an toàn.',ephemeral:true});}
async function testSelected(i){return i.reply({content:'🧪 Health được thực hiện từ nút HEALTH.',ephemeral:true});}
