import 'dotenv/config';
import http from 'node:http';
import {Client,GatewayIntentBits} from 'discord.js';
import {initDb,pool,listModels} from './db.js';
import {registerAdmin} from './admin.js';
const port=Number(process.env.PORT||10000);
const server=http.createServer(async(req,res)=>{if(req.url==='/health'){try{await pool.query('SELECT 1');res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,service:'discord-ai-council',version:'11.0.0'}));}catch(e){res.writeHead(503);res.end(JSON.stringify({ok:false,error:e.message}));}return;}res.writeHead(404);res.end('Not found');});
const client=new Client({intents:[GatewayIntentBits.Guilds]});
await initDb();
await registerAdmin(client);
client.once('ready',async()=>{const models=await listModels();console.log(`Discord AI Council ready as ${client.user.tag}; models=${models.length}`);});
server.listen(port,'0.0.0.0',()=>console.log(`Health server listening on ${port}`));
await client.login(process.env.DISCORD_TOKEN);
process.on('SIGTERM',async()=>{server.close();await pool.end();client.destroy();process.exit(0)});
