import {getSecret,listModels} from './db.js';
const catalogs={
 gemini:{label:'Google Gemini',base:'https://generativelanguage.googleapis.com/v1beta/models',free:true,desc:'Nhanh, đa phương thức, phù hợp chat/code và tác vụ dài.'},
 groq:{label:'Groq',base:'https://api.groq.com/openai/v1',free:true,desc:'Inference rất nhanh; phù hợp tác vụ cần phản hồi nhanh.'},
 openrouter:{label:'OpenRouter',base:'https://openrouter.ai/api/v1',free:true,desc:'Gateway nhiều model; có thể chọn các model có free tier.'},
 deepseek:{label:'DeepSeek',base:'https://api.deepseek.com',free:false,desc:'Mạnh về coding/reasoning; chỉ dùng khi API của bạn có hạn mức.'},
 openai:{label:'OpenAI',base:'https://api.openai.com/v1',free:false,desc:'General/reasoning/coding; dùng khi tài khoản có API credit.'},
 anthropic:{label:'Anthropic Claude',base:'https://api.anthropic.com/v1',free:false,desc:'Mạnh về coding, phân tích và agent; cần API access.'}
};
export function catalog(){return catalogs;}
async function json(res){const text=await res.text();let data={};try{data=JSON.parse(text)}catch{}if(!res.ok)throw new Error(data.error?.message||data.message||`HTTP ${res.status}`);return data;}
export async function chat(provider,model,messages){const cfg=await getSecret(provider);if(!cfg)throw new Error(`Provider ${provider} chưa được cấu hình.`);if(provider==='gemini'){const key=cfg.apiKey;const url=`${cfg.baseUrl||catalogs.gemini.base}/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;const contents=messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const system=messages.find(m=>m.role==='system')?.content;const body={contents};if(system)body.systemInstruction={parts:[{text:system}]};const data=await json(await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));return data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';}
 const base=(cfg.baseUrl||catalogs[provider]?.base||'').replace(/\/$/,'');const headers={'content-type':'application/json','authorization':`Bearer ${cfg.apiKey}`};if(provider==='anthropic'){headers['x-api-key']=cfg.apiKey;delete headers.authorization;headers['anthropic-version']='2023-06-01';}
 const data=await json(await fetch(`${base}/messages`,{method:'POST',headers,body:JSON.stringify({model,max_tokens:4096,messages:messages.filter(m=>m.role!=='system'),system:messages.find(m=>m.role==='system')?.content})}));return provider==='anthropic'?(data.content||[]).map(x=>x.text||'').join(''):data.choices?.[0]?.message?.content||'';}
export async function testProvider(provider,model){const started=Date.now();const text=await chat(provider,model,[{role:'user',content:'Reply with exactly: OK'}]);return {ok:/OK/i.test(text),latency:Date.now()-started,text:text.slice(0,80)};}
export function suggestedModels(provider){const x={gemini:[['gemini-2.5-flash','Nhanh, general/coding, phù hợp free-tier khi khả dụng','fast'],['gemini-2.5-pro','Reasoning và tác vụ khó','reasoning']],groq:[['openai/gpt-oss-120b','Open-weight reasoning/coding, inference nhanh','reasoning'],['llama-3.3-70b-versatile','General/coding nhanh','general']],openrouter:[['openrouter/free','Router tự chọn model free khả dụng','router']],deepseek:[['deepseek-chat','General/coding','coding'],['deepseek-reasoner','Reasoning khó','reasoning']],openai:[['gpt-4.1-mini','General/coding','coding']],anthropic:[['claude-sonnet-4-5','Coding, phân tích, agent','coding']]}[provider]||[];return x.map(([name,description,role])=>({name,description,role}));}
